# Generated by Django 4.2.7 on 2023-11-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'На модерации')], default=True, verbose_name='Активна'),
        ),
    ]
