# Generated by Django 4.2.7 on 2023-11-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_is_published', 'Can publish post'), ('set_description', 'Can change description'), ('set_category', 'Can change category')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(choices=[(True, 'Опубликовано'), (False, 'На модерации')], default=False, verbose_name='Опубликовано'),
        ),
    ]
